Repository themoment-team/hellogsm-server, pull requests merged in 2023-05, with the labels that each got.

#33 fix(global): Security Config 보완
  src/main/java/kr/hellogsm/back_v2/domain/user/enums/Role.java
  src/main/java/kr/hellogsm/back_v2/global/data/profile/ServerProfile.java
  src/main/java/kr/hellogsm/back_v2/global/security/SecurityConfig.java
Labels: priority: high, fix

#34 [#3] 원서 생성 기능 추가
  src/main/java/kr/hellogsm/back_v2/domain/application/controller/ApplicationController.java
  src/main/java/kr/hellogsm/back_v2/domain/application/dto/request/CreateApplicationReqDto.java
  src/main/java/kr/hellogsm/back_v2/domain/application/entity/Application.java
  src/main/java/kr/hellogsm/back_v2/domain/application/entity/admission/AdmissionInfo.java
  src/main/java/kr/hellogsm/back_v2/domain/application/entity/grade/GedAdmissionGrade.java
  src/main/java/kr/hellogsm/back_v2/domain/application/entity/grade/GraduateAdmissionGrade.java
  src/main/java/kr/hellogsm/back_v2/domain/application/entity/grade/MiddleSchoolGrade.java
  src/main/java/kr/hellogsm/back_v2/domain/application/entity/status/AdmissionStatus.java
  src/main/java/kr/hellogsm/back_v2/domain/application/repository/ApplicationRepository.java
  src/main/java/kr/hellogsm/back_v2/domain/application/service/CreateApplicationService.java
  src/main/java/kr/hellogsm/back_v2/domain/application/service/data/GedScoreData.java
  src/main/java/kr/hellogsm/back_v2/domain/application/service/data/GeneralScoreData.java
  src/main/java/kr/hellogsm/back_v2/domain/application/service/impl/CreateApplicationServiceImpl.java
  src/test/java/kr/hellogsm/back_v2/domain/application/entity/grade/GedAdmissionGradeMock.java
  src/test/java/kr/hellogsm/back_v2/domain/application/entity/grade/GedAdmissionGradeTest.java
  src/test/java/kr/hellogsm/back_v2/domain/application/entity/grade/GraduateAdmissionGradeMock.java
  src/test/java/kr/hellogsm/back_v2/domain/application/entity/grade/GraduateAdmissionGradeTest.java
Labels: feature, priority: high

#35 Refactoring 환경변수 객체와 Profile 별 환경변수
  .gitignore
  build.gradle
  src/main/java/kr/hellogsm/back_v2/HelloGsmBackV2Application.java
  src/main/java/kr/hellogsm/back_v2/global/schedule/ScheduleEnvironment.java
  src/main/java/kr/hellogsm/back_v2/global/security/SecurityConfig.java
  src/main/java/kr/hellogsm/back_v2/global/security/auth/AuthEnvironment.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/schedule.yml
Labels: refactor, priority: high

#39 User 권한 업데이트 중 잘못된 값이 들어가는 버그
  src/main/java/kr/hellogsm/back_v2/domain/identity/service/impl/CreateIdentityServiceImpl.java
Labels: bug, priority: high

#40 [#3] 원서 생성 기능 보완
  .gitignore
  src/main/java/kr/hellogsm/back_v2/domain/application/annotation/NotSpace.java
  src/main/java/kr/hellogsm/back_v2/domain/application/annotation/NotSpaceValidator.java
  src/main/java/kr/hellogsm/back_v2/domain/application/dto/request/CreateApplicationReqDto.java
  src/main/java/kr/hellogsm/back_v2/domain/application/entity/admission/AdmissionInfo.java
Labels: priority: high, fix

#46 [web:global/security] MapStruct 라이브러리 도입
  hellogsm-web/build.gradle
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/dto/domain/IdentityDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/dto/request/CreateIdentityReqDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/mapper/IdentityMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CreateIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/IdentityQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/dto/domain/UserDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/dto/mapper/UserMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/dto/request/CreateUserReqDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/CreateUserServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/ExistUserQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/UserByIdQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/UserByProviderQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/oauth/CustomOauth2UserService.java
Labels: feature, refactor, priority: high
