Repository themoment-team/hellogsm-server, pull requests merged in 2023-09, with the labels that each got.

#190 원서 성적 도메인 `@DecimalMin/Max` 설정 수정
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GraduateAdmissionGrade.java
Labels: priority: high, fix

#191 특정 기간 내 요청만 허용하는 Filter 구현
  hellogsm-web/src/main/java/team/themoment/hellogsm/HellogsmWebApplication.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/filter/TimeBasedFilter.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/schedule/ScheduleEnvironment.java
  hellogsm-web/src/main/resources/schedule.yml
Labels: feature, priority: high

#193 [#192] AdmissionGrade의 최대, 최소 지우기
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGrade.java
Labels: bug, priority: high

#194 원서 검색 기능 구현
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SearchApplicationResDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SearchApplicationsResDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/enums/SearchTag.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/SearchApplicationsService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/SearchApplicationsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: feature, test, priority: high

#195 fix: `identity/me/send-code-test` api 보안 설정 에러 해결
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
Labels: bug, priority: high, fix

#196 원서 리스트 검색 시 tag 없이 조회 가능한 기능 추가
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/SearchApplicationsServiceImpl.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: feature, priority: high

#198 [#197] ApplicationMapper 일부 필드 누락된 문제 해결
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
Labels: priority: high, fix

#199 logging 설정 추가
  .gitignore
  hellogsm-web/src/main/resources/logback-spring.xml
Labels: feature, priority: high

#200 엔티티 모듈 객체 javadoc `@author`, `@since` 태그 삭제
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/Application.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/AdmissionInfo.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/DesiredMajor.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGradeFactory.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GedAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GraduateAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/MiddleSchoolGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/data/GeneralScoreData.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/EvaluationStatus.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/Gender.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/GraduationStatus.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/Major.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/identity/entity/Identity.java
Labels: docs, priority: low

#201 `AdmissionGradeFactory#create` 에러 문구 수정
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGradeFactory.java
Labels: priority: low, fix

#202 엔티티 관련 객체 javadoc 추가
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/ScreeningCategory.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/data/GedScoreData.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/Screening.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/identity/event/UpdateIdentityEvent.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/user/entity/User.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/user/event/DeleteUserEvent.java
Labels: docs, priority: low

#203 Web 모듈 객체 Javadoc `@author`, `@since` 태그 삭제
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/annotation/NotSpace.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationReqDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/CreateApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/data/GeneralScoreData.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CreateApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/repository/IdentityRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/CreateIdentityService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/IdentityQuery.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/ModifyIdentityService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/AuthenticateCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CreateIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/IdentityQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/exception/GlobalExceptionHandler.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/exception/error/ExpectedException.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/exception/model/ExceptionResponseEntity.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthEnvironment.java
Labels: docs, priority: low

#204 엔티티 모듈 객체 javadoc 문구 보완
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/Application.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/DesiredMajor.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGradeFactory.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GedAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GraduateAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/MiddleSchoolGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/data/GeneralScoreData.java
Labels: docs, priority: low, fix

#206 applicaiton 리스트 조회 시 page 정보 반환하도록 변경
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/ApplicationListInfoDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ApplicationListQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/SearchApplicationsServiceImpl.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: priority: high, fix

#208 `GenerateCodeServiceImpl` 단위테스트 구현
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/service/impl/GenerateCodeServiceImplTest.java
Labels: test, priority: low

#207 `CreateIdentityServiceImpl` 단위테스트 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/service/impl/CreateIdentityServiceImplTest.java
Labels: test, priority: low

#205 web 모듈 일부 객체 javadoc 작성
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/CodeController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/AuthenticateCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CreateIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/controller/UserController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/exception/GlobalExceptionHandler.java
Labels: docs, priority: low

#210 어플리케이션 로그를 cloudwatch logs로 전송하는 기능 구현
  hellogsm-web/build.gradle
  hellogsm-web/src/main/resources/logback-spring.xml
Labels: feature, priority: high

#211 AWS X-ray 구성 추가
  hellogsm-web/build.gradle
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ApplicationListQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CascadeDeleteApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CreateApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DeleteApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/FinalSubmissionServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationForConsistencyImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationStatusServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QuerySingleApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QueryTicketsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/SearchApplicationsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/AuthenticateCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CascadeDeleteIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CreateIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/GenerateCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/GenerateTestCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/IdentityQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/ModifyIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/CreateUserServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/DeleteUserServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/ExistUserQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/UserByIdQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/UserByProviderQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/oauth/CustomOauth2UserService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/application/impl/ImageSaveServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/aws/impl/ImageUploadServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/aws/impl/SendSmsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/xray/XRayInspector.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/xray/config/AWSXRayConfig.java
Labels: feature, priority: high

#213 X-ray 인식 못하는 문제 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/repository/CodeRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/repository/IdentityRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/repository/UserRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/xray/XRayInspector.java
Labels: priority: high, fix

#214 logback 설정 변경
  hellogsm-web/src/main/resources/logback-spring.xml
Labels: priority: high, fix

#216 Batch 모듈 logback 설정 구현
  hellogsm-batch/src/main/resources/logback-spring.xml
Labels: feature, priority: high

#215 CloudWatch 관련 logback 설정 변경
  hellogsm-web/build.gradle
  hellogsm-web/src/main/resources/logback-spring.xml
Labels: feature, priority: high, fix

#209 Spring actuator 추가
  hellogsm-web/build.gradle
Labels: feature, priority: high

#219 원서 관련 서비스 javadoc 작성
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ApplicationListQuery.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/CascadeDeleteApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/CreateApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/DeleteApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/FinalSubmissionService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ImageSaveService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ModifyApplicationForConsistency.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ModifyApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ModifyApplicationStatusService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/QuerySingleApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/QueryTicketsService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/SearchApplicationsService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ApplicationListQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CascadeDeleteApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CreateApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DeleteApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/FinalSubmissionServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationForConsistencyImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationStatusServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QuerySingleApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QueryTicketsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/SearchApplicationsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/application/impl/ImageSaveServiceImpl.java
Labels: docs, priority: low

#222 Web user 도메인의 서비스 로직 javadoc 작성
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/CreateUserService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/DeleteUserService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/ExistUserQuery.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/UserByIdQuery.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/UserByProviderQuery.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/CreateUserServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/DeleteUserServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/ExistUserQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/UserByIdQueryImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/UserByProviderQueryImpl.java
Labels: docs, priority: low

#224 CreateApplicationServiceImpl 단위테스트 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/service/CreateApplicationServiceImplTest.java
Labels: test, priority: low

#226 DeleteApplicationServiceImpl 단위테스트 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/service/DeleteApplicationServiceImplTest.java
Labels: test, priority: low

#227 CreateApplicationServiceImpl 테스트코드 개선
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/service/CreateApplicationServiceImplTest.java
Labels: test, priority: low

#225 Web identity 도메인의 서비스 로직 javadoc 작성
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/AuthenticateCodeService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/CascadeDeleteIdentityService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/CodeNotificationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/CreateIdentityService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/GenerateCodeService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/IdentityQuery.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/ModifyIdentityService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/AuthenticateCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CascadeDeleteIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/GenerateCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/ModifyIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/aws/SendSmsService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/aws/impl/SendSmsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/identity/Impl/CodeNotificationServiceImpl.java
Labels: docs, priority: low

#230 `DeleteUserServiceImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/service/DeleteUserServiceImplTest.java
Labels: test, priority: low

#231 `ExistUserQueryImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/service/ExistUserQueryImplTest.java
Labels: test, priority: low

#234 `ApplicationRepository#findAllByIsFinalSubmittedAndPhoneNumberContaining` 쿼리 조건문 오류 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
Labels: bug, priority: high, fix

#232 `UserByIdQueryImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/service/UserByIdQueryImplTest.java
Labels: test, priority: low

#233 `UserByProviderQueryImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/service/UserByProviderQueryImplTest.java
Labels: test, priority: low

#235 feat: web, batch cd workflow 추가
  .github/workflows/hello-gsm-dev-batch-CD.yml
  .github/workflows/hello-gsm-dev-web-CD.yml
Labels: deploy

#236 workflow-dispatch 삭제
  .github/workflows/hello-gsm-dev-batch-CD.yml
  .github/workflows/hello-gsm-dev-web-CD.yml
Labels: deploy, fix

#237 cicd 파이프라인 구축
  .github/workflows/hello-gsm-dev-batch-CD.yml
  .github/workflows/hello-gsm-dev-web-CD.yml
  appspec.yml
  scripts/deploy.sh
  scripts/web-dev-deploy.sh
Labels: deploy

#238 QuerySingleApplicationServiceImpl 테스트 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/service/QuerySingleApplicationServiceImplTest.java
Labels: test, priority: low

#241 CD 이미 존재하는 경로 에러 수정
  .github/workflows/hello-gsm-dev-batch-CD.yml
  .github/workflows/hello-gsm-dev-web-CD.yml
Labels: deploy, fix

#248 prod batch/web cd workflow 추가
  .github/workflows/hello-gsm-prod-batch-CD.yml
  .github/workflows/hello-gsm-prod-web-CD.yml
Labels: deploy

#244 어드민/일반 사용자 분기처리 LogoutHandler 기능 구현
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/handler/CustomUrlLogoutSuccessHandler.java
Labels: feature, priority: high

#246 `ApplicationStatusReqDto` `@Pattern` 정규표현식 범위가 잘못 설정된 문제
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationStatusReqDto.java
Labels: priority: high, fix

#253 `HttpLoggingAspect` Pointcut 메서드가 null을 리턴한 경우 예외가 발생하는 문제 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/aop/logging/HttpLoggingAspect.java
Labels: priority: high, fix

#247 `CascadeDeleteIdentityServiceImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/service/impl/CascadeDeleteIdentityServiceImplTest.java
Labels: test, priority: low

#243 `AuthenticateCodeServiceImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/service/impl/AuthenticateCodeServiceImplTest.java
Labels: test, priority: low

#249 `IdentityQueryImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/service/impl/IdentityQueryImplTest.java
Labels: test, priority: low

#256 `CascadeDeleteIdentityServiceImplTest` 메서드와 객체 이름 변경
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/service/impl/CascadeDeleteIdentityServiceImplTest.java
Labels: test, priority: low

#252 `ModifyIdentityServiceImpl` 단위 테스트 코드 작성
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/service/impl/ModifyIdentityServiceImplTest.java
Labels: test, priority: low

#242 엑셀 다운로드 기능 추가
  hellogsm-web/build.gradle
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/DownloadExcelService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DownloadExcelServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: feature, priority: high

#258 누락된 기능인 admin 원서 수정 기능 추가
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: feature, priority: high

#259 원서 수정 요청 어드민 여부에 따라서 분기처리 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ModifyApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationServiceImpl.java
Labels: feature, priority: high, fix

#260 ApplicationControllerTest 누락된 ModifyApplicationService 변경사항 반영하도록 수정
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: priority: high, fix

#261 deploy if문 구문오류 수정
  scripts/deploy.sh
Labels: hotfix, deploy

#262 원서 수정 시 일부 데이터가 초기화되는 버그 해결
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationServiceImpl.java
Labels: bug, priority: high, fix

#263 cicd file path 수정
  appspec.yml
  scripts/web-dev-deploy.sh
  scripts/web-prod-deploy.sh
Labels: deploy

#264 SecurityConfig 인증/인가 엔드포인트 지정 잘못된 문제 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
Labels: priority: high, fix
