Repository themoment-team/hellogsm-server, pull requests merged in 2023-10, with the labels that each got.

#265 cicd script 파일 위치 수정
  scripts/deploy.sh
Labels: deploy

#266 cicd script 절대경로 -> 상대경로 변경
  .github/workflows/hello-gsm-prod-batch-CD.yml
  appspec.yml
  scripts/deploy.sh
  scripts/web-dev-deploy.sh
  scripts/web-prod-deploy.sh
Labels: deploy

#269 cicd workflow dispatch 추가
  .github/workflows/hello-gsm-dev-batch-CD.yml
  .github/workflows/hello-gsm-dev-web-CD.yml
  .github/workflows/hello-gsm-prod-batch-CD.yml
  .github/workflows/hello-gsm-prod-web-CD.yml
Labels: deploy

#271 web-deploy script jar파일 경로 변경
  scripts/web-dev-deploy.sh
  scripts/web-prod-deploy.sh
Labels: deploy

#272 Tester 권한추가 및 TimeBasedFilter 예외조건 추가
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/user/enums/Role.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/filter/TimeBasedFilter.java
Labels: feature, priority: high

#273 jar file deploy path 변경
  scripts/web-dev-deploy.sh
  scripts/web-prod-deploy.sh
Labels: deploy

#274 nohup output 경로 지정
  scripts/web-dev-deploy.sh
  scripts/web-prod-deploy.sh
Labels: deploy

#275 nohup output 명령어 수정
  scripts/web-dev-deploy.sh
  scripts/web-prod-deploy.sh
Labels: deploy

#254 `User`, `Identity` 도메인 엔티티 명 수정
  hellogsm-batch/src/main/resources/schema-mysql.sql
  hellogsm-batch/src/test/resources/data-bf.sql
  hellogsm-batch/src/test/resources/data-one.sql
  hellogsm-batch/src/test/resources/data-two.sql
  hellogsm-batch/src/test/resources/data.sql
  hellogsm-batch/src/test/resources/schema.sql
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/identity/entity/Identity.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/user/entity/User.java
Labels: refactor, priority: high

#276 X-Ray Trace ID 로그 설정 추가
  hellogsm-batch/src/main/resources/logback-spring.xml
  hellogsm-web/build.gradle
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/xray/config/AWSXRayConfig.java
  hellogsm-web/src/main/resources/logback-spring.xml
  hellogsm-web/src/main/resources/sampling-rules.json
Labels: feature, priority: high

#251 테스트코드의 메서드 이름을 더 자세하게 수정
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/service/CreateApplicationServiceImplTest.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/service/DeleteApplicationServiceImplTest.java
Labels: test, priority: low

#250 QuerySingleApplicationServiceImpl 테스트코드 수정
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/service/QuerySingleApplicationServiceImplTest.java
Labels: test, priority: low

#278 AWS SMS에 사용되는 maxPrice 설정값 제거
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/aws/impl/SendSmsServiceImpl.java
Labels: priority: high, fix

#277 엑셀 다운로드 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/DownloadExcelService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DownloadExcelServiceImpl.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: refactor, priority: high, fix

#279 2차 시험 평가 Query 오류 수정
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/jobSkillsEvaluation/JobSkillsEvaluationJobConfig.java
Labels: priority: high, fix

#280 엑셀 다운로드 api 재사용 오류 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DownloadExcelServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
Labels: hotfix, priority: high

#281 /user/me GET request ADMIN권한 추가
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
Labels: priority: high, fix

#282 졸업/졸업 예정자 중학교 예체능 성적 계산로직 버그 수정
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GraduateAdmissionGrade.java
Labels: priority: high, fix

#283 Web 원서 검색 기능에 합격 여부에 따른 정렬 기능을 추가
  dump.rdb
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/SearchApplicationsServiceImpl.java
Labels: feature, priority: high

#284 batch 모듈 logback 패턴에 x-ray trace id 설정 제거
  hellogsm-batch/src/main/resources/logback-spring.xml
Labels: priority: high, fix

#286 1차, 2차 평가 배치 - 탈락한 사용자는 n차 합격 전형 값을 null로 가지도록 변경
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/documentEvaluation/DocumentEvaluationJobConfig.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/jobSkillsEvaluation/JobSkillsEvaluationJobConfig.java
Labels: hotfix, priority: high

#287 엑셀 보호자전화번호 데이터 오류 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
Labels: hotfix, priority: high

#289 최종제출되지 않은 원서가 엑셀에 포함되는 현상 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DownloadExcelServiceImpl.java
Labels: hotfix, priority: high

#291 logout 기능 대체
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthController.java
Labels: hotfix, priority: high, fix

#292 [GET] application/search response body에 registrationNumber 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SearchApplicationResDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: hotfix, priority: high, fix

#293 20231019.0 버전 적용
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SearchApplicationResDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DownloadExcelServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthController.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: priority: high

#294 엑셀 최종점수 계산 방식 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
Labels: hotfix, priority: high

#295 엑셀 최종학과 셀 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DownloadExcelServiceImpl.java
Labels: feature, priority: high

#296 20231030.0 버전 적용
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DownloadExcelServiceImpl.java
Labels: priority: high
