Repository themoment-team/hellogsm-server, pull requests merged in 2023-06, with the labels that each got.

#51 [#49] 오타 수정 및 getter 추가
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/AdmissionInfo.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/DesiredMajor.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
Labels: bug, priority: high

#56 [#53] Application 하위 엔티티에 Enum 타입 필드 `@Enumerated` 누락
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/AdmissionInfo.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
Labels: bug, priority: high

#55 [#54] ApplicationReqDto 오타 수정 (.applicantBrith() -> .applicantBirth())
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationReqDto.java
Labels: bug, priority: high

#58 UserDto에 Security 관련 의존성 제거
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/dto/domain/UserDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/oauth/CustomOauth2UserService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/oauth/UserInfo.java
Labels: fix

#52 [#5, #9] 단일 원서 조회 기능 추가
  hellogsm-web/.gitignore
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/domain/AdmissionInfoDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/domain/AdmissionStatusDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/domain/GedAdmissionGradeDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/domain/GeneralAdmissionGradeDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/domain/SuperGrade.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/SingleApplicationRes.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/QuerySingleApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QuerySingleApplicationServiceImpl.java
Labels: feature, priority: high

#66 UserInfo, CustomOauth2UserService 리팩토링 및 `@AuthenticationPrincipal` 대체
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/controller/UserController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthenticatedUserManager.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthenticatedUserManagerImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/oauth/CustomOauth2UserService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/oauth/UserInfo.java
Labels: refactor, priority: high

#68 사용하지 않는 userInfo 파라미터 제거 및 import 제거
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
Labels: priority: low, fix

#69 Controllers 인증된 유저 정보를 사용하는 URI 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/controller/UserController.java
Labels: priority: high, fix

#72 IdentityController 오타 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
Labels: priority: high, fix

#70 close #61 Spring RestDocs 설정 및 UserController 테스트코드 추가
  hellogsm-entity/src/main/java/team/themoment/hellogsm/HellogsmEntityApplication.java
  hellogsm-web/build.gradle
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/controller/UserControllerTest.java
Labels: test, priority: high

#74 수정 `IdentityController#findByUserId()` 리턴 HTTP status code
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
Labels: priority: high, fix

#76 IdentityControllerTest 추가 및 API 작성,보완
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityControllerTest.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/controller/UserControllerTest.java
Labels: test, priority: high, fix

#79 entity 모듈 테스트 실행 불가 문제 해결
  hellogsm-entity/src/test/java/team/themoment/hellogsm/entity/HellogsmEntityApplicationTests.java
  hellogsm-entity/src/test/java/team/themoment/hellogsm/entity/domain/application/entity/HellogsmEntityTestConfiguration.java
Labels: priority: high, fix

#80 Rest Docs 관련 Test만 실행하는 Gradle Task 추가
  hellogsm-web/build.gradle
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityControllerTest.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/controller/UserControllerTest.java
Labels: test, priority: high, fix

#81 [#65] 적절하지 않은 파라미터 이름 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/QuerySingleApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QuerySingleApplicationServiceImpl.java
Labels: priority: low, fix

#82 [#10] 원서 삭제 기능 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/DeleteApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DeleteApplicationServiceImpl.java
Labels: feature, priority: high

#86 [#85] HttpMessageNotReadableException handling 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/exception/GlobalExceptionHandler.java
Labels: bug, priority: high

#84 [#13] 원서 상태 변경 기능 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationStatusReqDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ModifyApplicationStatusService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DeleteApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationStatusServiceImpl.java
Labels: feature, priority: high

#87 [#14] 수험표 출력 기능 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/TicketResDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/QueryTicketsService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QueryTicketsServiceImpl.java
Labels: feature, priority: high

#83 [#6] 모든 원서를 조회하는 기능을 추가했습니다
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/ApplicationListDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/ApplicationListInfoDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/ApplicationsDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/ApplicationListQuery.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ApplicationListQueryImpl.java
Labels: feature, priority: high

#94 Spring Security 인증, 인가 예외처리 구현
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/handler/CustomAccessDeniedHandler.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/handler/CustomAuthenticationEntryPoint.java
Labels: feature, priority: high

#90 AWS Dependancy 추가
  hellogsm-web/build.gradle
  hellogsm-web/src/main/resources/application-local.yml
  hellogsm-web/src/main/resources/application-prod.yml
Labels: docs, priority: high
