Repository themoment-team/hellogsm-server, pull requests merged in 2023-07, with the labels that each got.

#100 `spring-cloud-aws-test` 의존성 추가
  hellogsm-web/build.gradle
Labels: test, priority: high

#99 IdentityController 리다이렉트 시 Http Status Code 변경
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
Labels: priority: high, fix

#103 [#102] applicationController readOne 테스트 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#106 [#105] application controller readMe 테스트 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#108 사용하지 않는 통합테스트 클래스 비활성화
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/HellogsmBatchApplicationTests.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/HellogsmWebApplicationTests.java
Labels: test, priority: low, fix

#110 멀티모듈에 맞게 CI 설정
  .github/workflows/hello-gsm-back-CI.yml
Labels: priority: low, fix

#112 [#111] create, modify controller test 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#120 환경변수병 변경 REDIS_HOST -> HELLO_REDIS_HOST
  hellogsm-web/src/main/resources/application-local.yml
  hellogsm-web/src/main/resources/application-prod.yml
Labels: priority: low, fix

#114 application controller findall test 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#122 [#121] ApplicationController tickets test 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#119 [#118] applicationController delete test 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#124 [#123] ApplicationController image upload test 추가
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#126 원서 상태 엔티티에 지원 전형 상태 필드 추가
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/domain/AdmissionStatusDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationStatusReqDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/ApplicationsDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationStatusServiceImpl.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: feature, priority: high

#125 [#123] 예시 image url 수정
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: test, priority: low

#128 [#127] 최종제출 기능 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/FinalSubmissionService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/FinalSubmissionServiceImpl.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: feature, priority: high

#130 [#129] security config 설정 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/handler/CustomAccessDeniedHandler.java
Labels: priority: high, fix

#134 Screening 타입 추가 및 관련 DTO, 테스크코드 수정
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/Screening.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationReqDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationStatusReqDto.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: feature, priority: high, fix

#57 접수번호할당 배치 기능 추가
  hellogsm-batch/build.gradle
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/common/DateTimeParameter.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/config/BatchConfig.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/RegistrationNumberParameter.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/RegistrationNumberSequence.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfig.java
  hellogsm-batch/src/main/resources/application-local.yml
  hellogsm-batch/src/main/resources/application-prod.yml
  hellogsm-batch/src/main/resources/application.yml
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/HellogsmBatchApplicationTests.java
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/TestBatchConfig.java
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfigTest.java
Labels: feature, priority: high

#135 접수번호 생성 로직 오류 수정
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/RegistrationNumberSequence.java
Labels: priority: high, fix

#137 접수번호할당 배치 테스트 비활성화
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfigTest.java
Labels: test, priority: high

#138 [#136] 원서 변경 차단 기능 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/DeleteApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/FinalSubmissionServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/ModifyApplicationServiceImpl.java
Labels: priority: high, fix

#139 controller 테스트코드 리팩토링 및 restdocs 작성
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/common/ControllerTestUtil.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/controller/CodeControllerTest.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityControllerTest.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/controller/UserControllerTest.java
Labels: docs, refactor, test, priority: high

#141 API 명세서 누락된 문서 추가 및 공백 제거
  build.gradle
  hellogsm-batch/build.gradle
  hellogsm-entity/build.gradle
  hellogsm-web/build.gradle
  hellogsm-web/src/docs/asciidoc/index.adoc
Labels: docs, priority: low

#145 환경변수 설정 변경
  .gitignore
  hellogsm-batch/.gitignore
  hellogsm-batch/src/main/resources/application-local.yml
  hellogsm-batch/src/main/resources/application-prod.yml
  hellogsm-entity/.gitignore
  hellogsm-entity/src/main/resources/application-entity.yml
  hellogsm-web/.gitignore
  hellogsm-web/src/main/java/team/themoment/hellogsm/HellogsmWebApplication.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/data/profile/ServerProfile.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/schedule/ScheduleEnvironment.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/resources/application-local.yml
  hellogsm-web/src/main/resources/application-prod.yml
  hellogsm-web/src/main/resources/schedule.yml
Labels: priority: high, fix

#147 로깅 추가
  build.gradle
  hellogsm-web/src/main/java/team/themoment/hellogsm/HellogsmWebApplication.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/GenerateCodeServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/aop/logging/HttpLoggingAspect.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/aop/logging/ServiceLoggingAspect.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/exception/GlobalExceptionHandler.java
Labels: feature, priority: high

#146 OAuth 인증 handler 명확하게 변경
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthEnvironment.java
Labels: priority: high, fix

#148 H2Console url 허용 설정 제거
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
Labels: priority: high, fix

#149 웹 정적 파일에 대한 요청을 허용하는 설정 클래스 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/WebResourceConfig.java
Labels: feature, priority: high

#152 request 로깅 값에 User-Agent 정보 추기
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/aop/logging/HttpLoggingAspect.java
Labels: feature, priority: high

#151 API 명세서 API 환경 관련 문구 수정
  hellogsm-web/src/docs/asciidoc/index.adoc
Labels: docs, priority: low

#153 aws 예외처리 로직 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/aws/impl/ImageUploadServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/aws/impl/SendSmsServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/template/AwsCallBack.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/thirdParty/aws/service/template/AwsTemplate.java
Labels: feature, priority: high

#154 API 명세서 오타 수정 권환 -> 권한
  hellogsm-web/src/docs/asciidoc/index.adoc
Labels: docs, priority: low

#155 API 명세 `[GET] application/all` 누락 된 response-fields 추가
  hellogsm-web/src/docs/asciidoc/index.adoc
Labels: docs, priority: low
