Repository themoment-team/hellogsm-server, pull requests merged in 2023-08, with the labels that each got.

#157 ScreeningCategory 구현
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/ScreeningCategory.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/Screening.java
Labels: feature, priority: high

#156 원서 성적 관련 엔티티 nullable false로 변경 및 ApplicationController 리턴 타입 변경
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GedAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GraduateAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/MiddleSchoolGrade.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
Labels: refactor, priority: high

#158 원서 도메인 Nullalbe field가 Optional을 반환하도록 변경
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfig.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/common/util/OptionalUtils.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/AdmissionInfo.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
Labels: refactor, priority: high

#159 본인인증, 로그인, 로그아웃과 관련된 Redirect 기능 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/dto/response/CreateIdentityResDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/mapper/IdentityMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/CreateIdentityService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CreateIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthenticatedUserManager.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthenticatedUserManagerImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/controller/IdentityControllerTest.java
Labels: feature, priority: high, fix

#160 Domain 객체 Style 통일
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/Application.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/AdmissionInfo.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/DesiredMajor.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/AdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GedAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/GraduateAdmissionGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/MiddleSchoolGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/ScreeningCategory.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/data/GedScoreData.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/data/GeneralScoreData.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/enums/Screening.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/user/entity/User.java
Labels: refactor, priority: high

#161 도메인 Assert 문 message 수정
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/Application.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/AdmissionInfo.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/DesiredMajor.java
Labels: refactor, priority: high

#162 batch 구조 개선
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/common/BaseVersionParameter.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/common/DateTimeParameter.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/common/LoggingExceptionHandler.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/RegistrationNumberParameter.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/RegistrationNumberSequence.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfig.java
Labels: refactor, priority: high, fix

#163 entity(common) 모듈 의존성 설정 변경
  hellogsm-entity/build.gradle
Labels: priority: high, fix

#165 수험표 생성 로직 변경
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/TicketResDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/QueryTicketsService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/QueryTicketsServiceImpl.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: priority: high, fix

#167 api docs 수정 및 관련된 test code 수정
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: docs, test, priority: high, fix

#169 배치 모듈 테스트에 사용될 sql 추가
  hellogsm-batch/src/main/resources/data.sql
  hellogsm-batch/src/main/resources/schema.sql
Labels: feature, priority: high

#168 원서 id로 조회 로직 버그 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/repository/ApplicationRepository.java
Labels: priority: high, fix

#170 접수번호 할당 배치 로직 및 테스트코드 작성
  .gitignore
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfig.java
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/TestBatchConfig.java
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfigTest.java
  hellogsm-batch/src/test/resources/application-test.yml
  hellogsm-batch/src/test/resources/data.sql
  hellogsm-batch/src/test/resources/schema.sql
Labels: test, priority: high, fix

#171 CORS로 인한 에러 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
Labels: feature, priority: high

#172 테스트용 본인인증 코드 생성 서비스 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/controller/CodeController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/GenerateTestCodeService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/GenerateTestCodeServiceImpl.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/identity/controller/CodeControllerTest.java
Labels: priority: high, fix

#174 ApplicationMapper 잘못된 필드 사용 문제 해결
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
Labels: priority: high, fix

#175 Application 하위 엔티티 @GeneratedValue 어노테이션 제거
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/admission/AdmissionInfo.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/grade/MiddleSchoolGrade.java
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
Labels: priority: high, fix

#176 API 명세서에 휴대폰 본인인증 관련한 예외 발생 조건 정리
  hellogsm-web/src/docs/asciidoc/index.adoc
Labels: docs, priority: low

#178 유저 탈퇴기능 추가
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/user/event/DeleteUserEvent.java
  hellogsm-web/src/docs/asciidoc/index.adoc
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/CascadeDeleteApplicationService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/service/impl/CascadeDeleteApplicationServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/CascadeDeleteIdentityService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/identity/service/impl/CascadeDeleteIdentityServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/controller/UserController.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/event/DeleteUserEventHandler.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/DeleteUserService.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/user/service/impl/DeleteUserServiceImpl.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/user/controller/UserControllerTest.java
Labels: feature, priority: high

#179 AdmissionStatus의 screeningSubmittedAt 필드 삭제
  hellogsm-entity/src/main/java/team/themoment/hellogsm/entity/domain/application/entity/status/AdmissionStatus.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/domain/AdmissionStatusDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationStatusReqDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/response/ApplicationsDto.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/mapper/ApplicationMapper.java
  hellogsm-web/src/test/java/team/themoment/hellogsm/web/domain/application/controller/ApplicationControllerTest.java
Labels: priority: high, fix

#180 접수번호 할당 Batch Job Flow 수정
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfig.java
Labels: priority: high, fix

#181 접수번호 할당 배치 프로세스 로직에서 누락된 컬럼 추가
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfig.java
Labels: priority: high, fix

#182 최종학과 할당 배치 기능 구현
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setFinalMajor/MajorCapacity.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setFinalMajor/SetFinalMajorJobConfig.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/setFinalMajor/SetFinalMajorParameter.java
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/jobs/setFinalMajor/SetFinalMajorJobConfigTest.java
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/jobs/setRegistrationNumber/SetRegistrationNumberJobConfigTest.java
  hellogsm-batch/src/test/resources/application-test-bf.yml
  hellogsm-batch/src/test/resources/application-test-one.yml
  hellogsm-batch/src/test/resources/application-test-two.yml
  hellogsm-batch/src/test/resources/application.yml
  hellogsm-batch/src/test/resources/data-bf.sql
  hellogsm-batch/src/test/resources/data-one.sql
  hellogsm-batch/src/test/resources/data-two.sql
Labels: feature, test, priority: high

#183 1차 전형(서류전형) 평가 기능 구현
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/common/EvaluationDecisionProvider.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/common/EvaluationResult.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/documentEvaluation/DocumentEvaluationJobConfig.java
  hellogsm-batch/src/main/java/team/themoment/hellogsm/batch/jobs/documentEvaluation/DocumentEvaluationParameter.java
  hellogsm-batch/src/test/java/team/themoment/hellogsm/batch/jobs/documentEvaluation/DocumentEvaluationJobConfigTest.java
  hellogsm-batch/src/test/resources/data-bf.sql
  hellogsm-batch/src/test/resources/data-one.sql
  hellogsm-batch/src/test/resources/data-two.sql
Labels: feature, test, priority: high

#185 [#184] telephone dto 수정
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/domain/application/dto/request/ApplicationReqDto.java
Labels: bug

#186 어드민 로그인 시 어드민 페이지로 리다이렉트 기능 추가
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/SecurityConfig.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/auth/AuthEnvironment.java
  hellogsm-web/src/main/java/team/themoment/hellogsm/web/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
Labels: feature, priority: high
